verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"
notify                   = { say-on-exit = false }
globbing                 = { ignores = ['.doot_ignore', '.git', '.DS_Store', "__pycache__"] }
subtask                  = { sleep = 1 }
batch                    = { sleep = 1 }
zip                      = { level = 5 }

[logging]
stream = { level = "INFO", format  = "{levelname:<8} : {message}", filters = ["doot", "bkmkorg", "code_analysis", "scrapy"] }
file   = { level = "DEBUG", format = "{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})", filters =  ["doot", "bkmkorg", "code_analysis", "scrapy"] }

[[directories]] # Core
src         = "code_analysis"
codegen     = "code_analysis/_codegen"
temp        = ".temp"
build       = "build"
docs        = "docs"

[[directories]] # Data
data        = "data"
raw         = "data/raw"
crawled     = "data/crawled"
extractions = "build/extractions"

[[directories]] # backups
backup      = "/volumes/BackupSD/Archive/datasets"
SD_backup   = "/volumes/BackupSD/Archive/datasets"

# [[directories]] # PC
# steam_1     = "/volumes/SteamLibrary"
# steam_2     = "/volumes/SteamLibrary2"
# steam_3     = "/volumes/SteamLibrary3"
# steam_4     = "/volumes/steamapps"
# origin      = "/volumes/origin"
# gog         = "/volumes/gog"
# viva_pinata = "/volumes/Viva Pinata"

[group.hashing]
[group.pip]
[group.python]
