# -*- mode:conf-toml; -*-
[settings.general]
notify                   = { say-on-exit = false }
loaders                  = { commands="default", task="default", parser="default"}
location_check           = { make_missing = true, print_levels={action="WARN", execute="WARN" } }


[settings.tasks]
sources = [".tasks"]               # Files or locations where task specs can be loaded from, expanded according to [[locations]] keys
code    = ["./", ".tasks/"]         # Directories where task specific code can be imported from, expanded according to [[locations]] keys
sleep   = { task=0.2, subtask=1, batch=1 }

[logging]
stream  = { level="WARN",  allow=["doot"], format="{levelname:<8} : {message}", colour=true }
file    = { level="DEBUG", allow=["doot"], format="{levelname:<8} : {message:<20} :|: (module:{module} line:{lineno} fn:{funcName})" }
printer = { level="INFO", colour=true}


[[locations]] # Core
src         = "corana"
codegen     = "{src}/_codegen"
temp        = ".temp"
docs        = "docs"

[[locations]] # Data
packed_data   = "/media/john/data/datasets/"
data          = "data"
raw           = "{data}/raw"
crawled       = "{data}/crawled"

[[locations]] # backups
backup      = "/media/john/big_ex/datasets"
