verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"

[tool.doot]
say-on-exit   = false
glob_ignores  = ['.git', '.DS_Store', "__pycache__"]
subtask-sleep = 1
batch-sleep   = 1

[tool.doot.directories]
src         = "code_analysis"
codegen     = "code_analysis/_codegen"
temp        = ".temp"
build       = "build"
docs        = "docs"
data        = "data/raw"
backup      = "data/backups"
SD_backup   = "/volumes/BackupSD/Archive/new_code_backups"
