
[[tasks.basic]]
name                 = "preserve.data"
version              = "0.1"                                           # <str>
ctor                 = "task"                                          # <type>
cli                  = [
                     {name="target", type="str", default="None", prefix="--"},
]
doc                  = ["Ensure all files except metadata in {raw} are read-only"] # <list[str]>
depends_on           = []                                              # <list[DootTaskArtifact]>
actions              = [
                     {do="log", msg="Forcing all raw files to read-only"},
                     {do="provenance.actions.basic:readonly_raw"}
]                                              # <list[Any]>


[[tasks.basic]]
name                 = "list"
version              = "0.1"                                           # <str>
ctor                 = "task"                                          # <type>
cli                  = [ {name="target", type="str", default="None", prefix="--"} ]
doc                  = [] # <list[str]>
depends_on           = []                                              # <list[DootTaskArtifact]>
actions              = [
                     {do="provenance.actions.basic:gather_data", from="{backup}", update_="zips"},
                     {do="provenance.actions.basic:cli_or_select", from_="zips", update_="selected"},
                     {do="provenance.actions.basic:UnpackData", from_="selected"}
]                                              # <list[Any]>

[[tasks.basic]]
name                 = "pack"
version              = "0.1"                                           # <str>
ctor                 = "task"                                          # <type>
doc                  = [] # <list[str]>
cli                  = [ {name="target", type="str", default="None", prefix="--"} ]
depends_on           = []                                              # <list[DootTaskArtifact]>
actions              = [
                     {do="provenance.actions.basic:gather_unpacked"},
                     {do="provenance.actions.basic:PackData"}
]                                              # <list[Any]>
